name: Build cross-platform apps with PyInstaller

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-22.04, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Linux-specific dependencies for PyInstaller
      - name: Install Linux build tools
        if: matrix.os == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-dev python3-tk libglib2.0-dev libnss3 libatk-bridge2.0-0 libx11-xcb1 patchelf

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask requests selenium pandas psutil pyngrok google-generativeai pyinstaller webdriver-manager
          python -m pip install --force-reinstall --extra-index-url https://PySimpleGUI.net/install PySimpleGUI

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile client_bot.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-bot-${{ matrix.os }}
          path: dist/*
